services:
  eureka:
    image: eedoy/eureka:latest
    container_name: eureka
    ports:
      - "8761:8761"
    environment:
      - TZ=Asia/Seoul
    restart: always

  gateway:
    image: eedoy/gateway:latest
    container_name: gateway
    depends_on:
      - eureka
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    restart: always
