server:
  port: 8000

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          uri: lb://ORDER-SERVICE
        - id: PAYMENT-SERVER
          predicates:
            - Path=/api/v1/payments/**
          uri: lb://PAYMENT-SERVER

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
