spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes: # ??? ??
        - id: order-service # ???? ?? id??? ??? ???? ??
          predicates: # ??? ??
            - Path=/first-service/** # first-service/ ?? ??? ????
          uri: lb://DEMO-EUREKA-CLIENT # ??? ???? DEMO-EUREKA-CLIENT? ??? ???? ??? ???.
          filters:
            # url ???
            # ?<???>? ?? ??? ???? ???? ??? ? ??? ??. ()? ??? ?? ?? -> segment? (.*)? ??
            # ??(,)? ???? ?? url? ??? url? ?????.
            # ?? ?? ??? ??? ${???}?? url ???? ?? / ?????? ?? ??.
            - RewritePath=/first-service/(?<segment>.*), /$\{segment}
        - id: payment-service
          predicates:
            - Path=/second-service/**
          uri: lb://DEMO-EUREKA-CLIENT2
          filters:
            - RewritePath=/second-service/(?<segment>.*), /$\{segment}
