spring:
  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          uri: lb://ORDER-SERVICE

        - id: PAYMENT-SERVER
          predicates:
            - Path=/api/v1/payments/**
          uri: lb://PAYMENT-SERVER

        - id: USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          uri: lb://USER-SERVICE

        - id: STORE-SERVICE
          predicates:
            - Path=/api/v1/stores/**
          uri: lb://STORE-SERVICE

        - id: RECRUITMENT-SERVICE
          predicates:
            - Path=/api/v1/recruitments/**
          uri: lb://RECRUITMENT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.36.183.156:8761/eureka

