server:
  port: 8000

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          uri: http://54.66.149.225:8100

        - id: PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**
          uri: http://34.127.7.212:8101

        - id: USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          uri: http://54.66.149.225:8104

        - id: STORE-SERVICE
          predicates:
            - Path=/api/v1/stores/**
          uri: http://54.66.149.225:8103

        - id: RECRUITMENT-SERVICE
          predicates:
            - Path=/api/v1/recruitments/**
          uri: http://34.127.7.212:8102
