server:
  port: 8100

spring:
  application:
    name: ORDER-SERVICE

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.36.183.156:8761/eureka/

