spring:
  application:
    name: RECRUITMENT-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/recruitment_db?serverTimezone=Asia/Seoul
    username: root
    password: 040320
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
